import sys
from time import gmtime, strftime

#
# generated filenames
#

class FilenameProvider:
	def __init__(self, documentation):
		self.documentation = documentation

	def type(self, dotnetType):
		return "T_" + self.documentation.TypeFullName(dotnetType) + ".html"

	def namespace(self, str):
		return "N_" + str + ".html"


class HtmlTemplate:
	def __init__(self):
		self.title  = ""
		self.h1     = ""
		self.header = ""
		self.main   = ""
		self.footer = ""

	def write(self):
		return """<html>
				<head>
					<title>%s</title>
				</head>
				<body>
					<h1>%s</h1>
					<!-- header -->
					<header>
					%s
					</header>
					<!-- main area -->
					<section>
					%s
					</section>
					<!-- footer -->
					<footer>
					%s
					</footer>
				</body>
			</html>
	""" % (self.title, self.h1, self.header, self.main, self.footer)

	def writeTo(self, file):
		f = open(file, 'w')
		f.write(self.write())
		f.close()


class HtmlGenerator:
	def __init__(self, documentation):
		self.documentation = documentation
		self.filenameProvider = FilenameProvider(documentation)
		self.htmlTemplate = HtmlTemplate()
		self.htmlTemplate.header = self.nav()
		self.htmlTemplate.footer = """Generated by IglooCastle at
			""" + strftime("%Y-%m-%d %H:%M:%S", gmtime()) + """
			<link type=\"text/css\" rel=\"stylesheet\" href=\"style.css\" />
			</footer>"""

	def generateIndexPage(self):
		pass

	def generateNamespacePages(self):
		print "Namespaces:"
		for namespaceElement in self.documentation.Namespaces:
			namespace = namespaceElement.Namespace
			print namespace

			self.htmlTemplate.title = namespace
			self.htmlTemplate.h1 = namespace
			self.htmlTemplate.writeTo(self.filenameProvider.namespace(namespace))

	def generateTypePages(self):
		print "Types:"
		for typeElement in self.documentation.Types:
			fullName = self.documentation.TypeFullName(typeElement.Type)
			print fullName
			self.htmlTemplate.title = "Type " + fullName
			self.htmlTemplate.h1    = "Type " + fullName
			self.htmlTemplate.main  = """
					<p>""" + typeElement.XmlComment.Summary + """</p>
					""" + self.typeProperties(typeElement) + self.typeMethods(typeElement)
			self.htmlTemplate.writeTo(self.filenameProvider.type(typeElement.Type))

	def generateNantTaskPages(self):
		print "NAnt tasks:"
		for typeElement in self.documentation.Types:
			if typeElement.HasAttribute('NAnt.Core.Attributes.TaskName'):
				taskName = typeElement.GetAttribute('NAnt.Core.Attributes.TaskName').Name
				print "todo: generate page for nant task " + taskName



	#
	# linking
	#

	def typeLink(self, t):
		typeFullName = self.documentation.TypeFullName(t)
		print "Type %s, full name %s" % (t, typeFullName)

		if self.documentation.IsLocalType(t):
			link = self.filenameProvider.type(t)
			print link
			return "<a href=\"" + link + "\">" + typeFullName + "</a>"
		else:
			print typeFullName
			return typeFullName

	#
	# core
	#

	def memberListItem(self, typeElement, memberElement):
		if memberElement.Member.DeclaringType != typeElement.Type:
			inheritedLink = "(inherited from %s)" % self.typeLink(memberElement.Member.DeclaringType)
		else:
			inheritedLink = ""

		result = """<li>
			<dl>
				<dt>%s</dt>
				<dd>%s %s</dd>
			</dl>
		</li>""" % (memberElement.Member.Name, memberElement.XmlComment.Summary, inheritedLink)

		return result

	def typeProperties(self, typeElement):
		print 'typeProperties'
		if not len(typeElement.Properties):
			return ""

		result = ''.join(self.memberListItem(typeElement, p) for p in typeElement.Properties)
		if len(result):
			result = "<h2>Properties</h2><ul>" + result + "</ul>"

		return result


	def typeMethods(self, typeElement):
		print 'typeMethods'
		result = ""
		for p in typeElement.Methods:
			result = result + self.memberListItem(typeElement, p)
		if len(result):
			result = "<h2>Methods</h2><ul>" + result + "</ul>"

		return result

	def nav(self):
		result = ""
		for t in self.documentation.Types:
			result = result + "<li>" + self.typeLink(t.Type) + "</li>"
		if len(result):
			result = "<nav><ul>" + result + "</ul></nav>"

		return result


def Generate(documentation):
	print "Hello from python!"
	htmlGenerator = HtmlGenerator(documentation)
	htmlGenerator.generateIndexPage()
	htmlGenerator.generateNamespacePages()
	htmlGenerator.generateTypePages()
	htmlGenerator.generateNantTaskPages()
